#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zope.location
Version  : 4.1.0
Release  : 14
URL      : https://pypi.python.org/packages/15/59/54b254aa3c820d778ec68b19082b7cc2b41bacb795c867641e6c15540950/zope.location-4.1.0.tar.gz
Source0  : https://pypi.python.org/packages/15/59/54b254aa3c820d778ec68b19082b7cc2b41bacb795c867641e6c15540950/zope.location-4.1.0.tar.gz
Summary  : Zope Location
Group    : Development/Tools
License  : ZPL-2.1
Requires: zope.location-python3
Requires: zope.location-license
Requires: zope.location-python
Requires: Sphinx
Requires: setuptools
Requires: zope.component
Requires: zope.configuration
Requires: zope.interface
Requires: zope.proxy
Requires: zope.schema
Requires: zope.testrunner
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : zope.event
BuildRequires : zope.interface
BuildRequires : zope.proxy
BuildRequires : zope.schema

%description
``zope.location``
        ===================

%package license
Summary: license components for the zope.location package.
Group: Default

%description license
license components for the zope.location package.


%package python
Summary: python components for the zope.location package.
Group: Default
Requires: zope.location-python3

%description python
python components for the zope.location package.


%package python3
Summary: python3 components for the zope.location package.
Group: Default
Requires: python3-core

%description python3
python3 components for the zope.location package.


%prep
%setup -q -n zope.location-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529091698
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/zope.location
cp LICENSE.txt %{buildroot}/usr/share/doc/zope.location/LICENSE.txt
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/zope.location/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
